local mod = get_mod("Crosshair Kill Confirmation")

return {
	name = "Crosshair Kill Confirmation",           -- Readable mod name
	description = mod:localize("mod_description"),  -- Mod description
	is_togglable = true,                            -- If the mod can be enabled/disabled
	options = {                                     -- Widget settings for the mod options menu
		widgets = {
			{
				setting_id = "duration",
				type = "numeric",
				default_value = 1,
				range = {0, 4},
				decimals_number = 2,
			},
			{
				setting_id = "size",
				type = "numeric",
				default_value = 52,
				range = {0, 128},
				decimals_number = 0,
			},
			{
				setting_id = "pop",
				type = "numeric",
				default_value = 2.2,
				range = {1, 10},
				decimals_number = 1,
			},
			{
				setting_id = "crosshair_normal",
				type = "dropdown",
				default_value = "ex",
				options = {
					{text="option_circle", value="circle"},
					{text="option_dot", value="dot"},
					{text="option_ex", value="ex"},
					{text="option_plus", value="plus"},
					{text="option_square", value="square"},
					{text="option_triangle", value="triangle"},
					{text="option_heart", value="heart"},
					{text="option_none", value="none"},
				},
			},
			{
				setting_id = "crosshair_special",
				type = "dropdown",
				default_value = "circle",
				options = {
					{text="option_circle", value="circle"},
					{text="option_dot", value="dot"},
					{text="option_ex", value="ex"},
					{text="option_plus", value="plus"},
					{text="option_square", value="square"},
					{text="option_triangle", value="triangle"},
					{text="option_heart", value="heart"},
					{text="option_none", value="none"},
				},
			},
			{
				setting_id = "crosshair_elite",
				type = "dropdown",
				default_value = "triangle",
				options = {
					{text="option_circle", value="circle"},
					{text="option_dot", value="dot"},
					{text="option_ex", value="ex"},
					{text="option_plus", value="plus"},
					{text="option_square", value="square"},
					{text="option_triangle", value="triangle"},
					{text="option_heart", value="heart"},
					{text="option_none", value="none"},
				},
			},
			{
				setting_id = "crosshair_boss",
				type = "dropdown",
				default_value = "square",
				options = {
					{text="option_circle", value="circle"},
					{text="option_dot", value="dot"},
					{text="option_ex", value="ex"},
					{text="option_plus", value="plus"},
					{text="option_square", value="square"},
					{text="option_triangle", value="triangle"},
					{text="option_heart", value="heart"},
					{text="option_none", value="none"},
				},
			},
			{
				setting_id = "KILL_MARKERS_REGULAR_COLOR_GROUP",
				type = "group",
				tooltip = "KILL_MARKERS_REGULAR_COLOR_GROUP_T",
                                default_value = true,
                                sub_widgets = {
                                   {
						setting_id = "redregular",
						type = "numeric",
						text = mod:localize("red"),
						tooltip = "custom_red_tooltip",
						range = {0, 255},
						default_value = 255,
 						},
                                   {
						setting_id = "greenregular",
						type = "numeric",
						text = mod:localize("green"),
						tooltip = "custom_green_tooltip",
						range = {0, 255},
						default_value = 255,
 						},
                                   {
						setting_id = "blueregular",
						type = "numeric",
						text = mod:localize("blue"),
						tooltip = "custom_blue_tooltip",
						range = {0, 255},
						default_value = 255,
 						},
                                   },
			},
			{
				setting_id = "KILL_MARKERS_DOT_COLOR_GROUP",
				type = "group",
				tooltip = "KILL_MARKERS_DOT_COLOR_GROUP_T",
                                default_value = true,
                                sub_widgets = {
                                   {
						setting_id = "reddot",
						type = "numeric",
						text = mod:localize("red"),
						tooltip = "custom_red_tooltip",
						range = {0, 255},
						default_value = 170,
 						},
                                   {
						setting_id = "greendot",
						type = "numeric",
						text = mod:localize("green"),
						tooltip = "custom_green_tooltip",
						range = {0, 255},
						default_value = 25,
 						},
                                   {
						setting_id = "bluedot",
						type = "numeric",
						text = mod:localize("blue"),
						tooltip = "custom_blue_tooltip",
						range = {0, 255},
						default_value = 255,
 						},
                                   },
			},
			{
				setting_id = "KILL_MARKERS_HEAD_COLOR_GROUP",
				type = "group",
				tooltip = "KILL_MARKERS_HEAD_COLOR_GROUP_T",
                                default_value = true,
                                sub_widgets = {
                                   {
						setting_id = "redhead",
						type = "numeric",
						text = mod:localize("red"),
						tooltip = "custom_red_tooltip",
						range = {0, 255},
						default_value = 255,
 						},
                                   {
						setting_id = "greenhead",
						type = "numeric",
						text = mod:localize("green"),
						tooltip = "custom_green_tooltip",
						range = {0, 255},
						default_value = 100,
 						},
                                   {
						setting_id = "bluehead",
						type = "numeric",
						text = mod:localize("blue"),
						tooltip = "custom_blue_tooltip",
						range = {0, 255},
						default_value = 25,
 						},
                                   },
			},
			{
				setting_id = "KILL_MARKERS_CRITICAL_COLOR_GROUP",
				type = "group",
				tooltip = "KILL_MARKERS_CRITICAL_COLOR_GROUP_T",
                                default_value = true,
                                sub_widgets = {
                                   {
						setting_id = "redcrit",
						type = "numeric",
						text = mod:localize("red"),
						tooltip = "custom_red_tooltip",
						range = {0, 255},
						default_value = 255,
 						},
                                   {
						setting_id = "greencrit",
						type = "numeric",
						text = mod:localize("green"),
						tooltip = "custom_green_tooltip",
						range = {0, 255},
						default_value = 25,
 						},
                                   {
						setting_id = "bluecrit",
						type = "numeric",
						text = mod:localize("blue"),
						tooltip = "custom_blue_tooltip",
						range = {0, 255},
						default_value = 25,
 						},
                                   },
			},
			{
				setting_id = "KILL_MARKERS_HS_AND_CRIT_COLOR_GROUP",
				type = "group",
				tooltip = "KILL_MARKERS_HS_AND_CRIT_COLOR_GROUP_T",
                                default_value = true,
                                sub_widgets = {
                                   {
						setting_id = "redcrithead",
						type = "numeric",
						text = mod:localize("red"),
						tooltip = "custom_red_tooltip",
						range = {0, 255},
						default_value = 0,
 						},
                                   {
						setting_id = "greencrithead",
						type = "numeric",
						text = mod:localize("green"),
						tooltip = "custom_green_tooltip",
						range = {0, 255},
						default_value = 0,
 						},
                                   {
						setting_id = "bluecrithead",
						type = "numeric",
						text = mod:localize("blue"),
						tooltip = "custom_blue_tooltip",
						range = {0, 255},
						default_value = 0,
 						},
                                   },
			},
			{
				setting_id = "KILL_MARKERS_ASSISTS_COLOR_GROUP",
				type = "group",
				tooltip = "KILL_MARKERS_ASSISTS_COLOR_GROUP_T",
                                default_value = true,
                                sub_widgets = {
                                   {
						setting_id = "redassist",
						type = "numeric",
						text = mod:localize("red"),
						tooltip = "custom_red_tooltip",
						range = {0, 255},
						default_value = 7,
 						},
                                   {
						setting_id = "greenassist",
						type = "numeric",
						text = mod:localize("green"),
						tooltip = "custom_green_tooltip",
						range = {0, 255},
						default_value = 150,
 						},
                                   {
						setting_id = "blueassist",
						type = "numeric",
						text = mod:localize("blue"),
						tooltip = "custom_blue_tooltip",
						range = {0, 255},
						default_value = 210,
 						},
                                   },
			},
		}
	}
}
